name: "Release version"

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    if: github.ref_name == 'main'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: debug
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        run: |
          echo $GITHUB_TOKEN

      - name: Release
        # env:
        #   GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        run: npx semantic-release --generate-notes
